apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: sbedx4/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.js'
            dest: .
    - image: sbedx4/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: sbedx4/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: sbedx4/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: sbedx4/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: sbedx4/query
        context: query
        docker:
          dockerfile: Dockerfile
        sync:
          manual: 
            - src: '*.js'
              dest: .